---
# This is an example for newton
os_release:
  vm_name: 'newton'
  os_release: 'stable/newton'
  public_ip: '192.168.27.100'
  floating_ip_net: '172.24.4.225'
  floating_ip_range: '172.24.4.0/24'
  floating_ip_netmask: '255.255.255.0'
  floating_ip_gw: '172.24.4.1'
folder_mount:
  - name: Project 1
    src: path_to_project1_on_host
    dst: path_to_project1_on_guest
  - name: Project 2
    src: path_to_project2_on_host
    dst: path_to_project2_on_guest
