---
- hosts: default
  vars:
    devstack_repo: git://github.com/openstack-dev/devstack.git
    heat: False
    neutron: True
    neutron_lbaasv2: False
    swift: False
    security_groups: False
    tempest: False
    keyring_config_dir: /home/vagrant/.local/share/python_keyring
    app_catalog: False
    ceilometer: True
    hostname: devstack
    ## Following variables are passed from the Vagrantfile or via --extra-vars
    # public_ip: 192.168.27.100
    # floating_ip_range: 172.24.4.0/24
    # version: stable/newton

  tasks:
    - fail: msg="Variable '{{ item }}' is not defined"
      when: item not in vars
      with_items:
         - version
         - public_ip
         - floating_ip_range
         - floating_ip_gw

    - name: set hostname
      become: True
      hostname:
        name={{ hostname }}

    - name: create keyring config directory
      file: >
        state=directory
        dest={{ keyring_config_dir }}

    - name: copy keyring config file to workaround https://bugs.launchpad.net/bugs/1242992
      copy: >
        src=files/keyringrc.cfg
        dest={{ keyring_config_dir }}/keyringrc.cfg

    - name: install git
      apt: "name=git update_cache=yes"
      become: True

    - name: checkout devstack
      git: repo={{ devstack_repo }} dest=/home/vagrant/devstack version={{ version }} accept_hostkey=yes

    - name: local.conf
      template: src=templates/local.conf.j2 dest=/home/vagrant/devstack/local.conf

    - name: source openrc in profile
      lineinfile: dest=/home/vagrant/.profile regexp=".*openrc" line='. /home/vagrant/devstack/openrc'

    - name: enable eth2
      command: ip link set dev eth2 up
      become: True

