# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'
current_dir = File.dirname(File.expand_path(__FILE__))
configs = YAML.load_file("#{current_dir}/config.yaml")
mounts = YAML.load_file("#{current_dir}/mounts.yaml")
# Variables
vm_name = configs['os_release']['vm_name']
os_release = configs['os_release']['os_release']
public_ip = configs['os_release']['public_ip']
floating_ip_net = configs['os_release']['floating_ip_net']
floating_ip_range = configs['os_release']['floating_ip_range']
floating_ip_netmask = configs['os_release']['floating_ip_netmask']
floating_ip_gw = configs['os_release']['floating_ip_gw']

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.hostname = vm_name
    config.ssh.forward_agent = true
    # eth1, this will be the endpoint
    config.vm.network :private_network, ip: public_ip
    # eth2, this will be the OpenStack "public" network
    # ip and subnet mask should match floating_ip_range var in devstack.yml
    config.vm.network :private_network, ip: floating_ip_net, :netmask => floating_ip_netmask, :auto_config => false
    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", 6144]
        vb.customize ["modifyvm", :id, "--cpus", 2]
        # eth2 must be in promiscuous mode for floating IPs to be accessible
        vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
    end
    config.vm.provision :ansible do |ansible|
        ansible.host_key_checking = false
        ansible.playbook = "../ansible-devstack/devstack.yml"
        ansible.verbose = "v"
        ansible.extra_vars = {
            version: os_release,
            public_ip: public_ip,
            floating_ip_range: floating_ip_range,
            floating_ip_gw: floating_ip_gw,
            hostname: vm_name
        }
    end
    config.vm.provision :shell, :inline => "cd devstack; sudo -u vagrant env HOME=/home/vagrant ./stack.sh"
    config.vm.provision :shell, :inline => "ovs-vsctl add-port br-ex eth2"
    config.vm.provision :shell, :inline => "virsh net-destroy default"

    # Mount the main folder of this project
    config.vm.synced_folder "../", "/home/vagrant/finext-region-testenv"

    # Per project folder mounting. Here is possible to mount the folder of repositories have to be tested inside this OpenStack environment
    mounts['folder_mount'].each do |prj|
        config.vm.synced_folder prj['src'], prj['dst']
    end
end